create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  name text not null,
  cuisine text not null default '江浙菜',
  region text not null,
  province text,
  city text,
  seasons text[] not null default '{}',
  taste_tags text[] not null default '{}',
  course_type text not null check (course_type in ('dish', 'soup')),
  cook_minutes int not null check (cook_minutes > 0),
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists idx_recipes_region on public.recipes(region);
create index if not exists idx_recipes_course_type on public.recipes(course_type);
create index if not exists idx_recipes_active on public.recipes(is_active);
create index if not exists idx_recipes_seasons_gin on public.recipes using gin (seasons);
create index if not exists idx_recipes_taste_tags_gin on public.recipes using gin (taste_tags);
create unique index if not exists idx_recipes_name_cuisine_uniq on public.recipes(name, cuisine);

alter table public.recipes enable row level security;

create policy if not exists "Authenticated users can read recipes"
on public.recipes
for select
to authenticated
using (is_active = true);
